// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCf6JNTt5nIrsWpaaYcRUn7-oDvFonDyA',
    appId: '1:462143934523:web:c3f48aedcf64dfaf27cc1e',
    messagingSenderId: '462143934523',
    projectId: 'fir-a2f69',
    authDomain: 'fir-a2f69.firebaseapp.com',
    storageBucket: 'fir-a2f69.appspot.com',
    measurementId: 'G-4Q9T48ZGRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbBsJ8Dps2meO_KBCEagWwOu9dFR4MYY',
    appId: '1:462143934523:android:33dd7064a4ee83bd27cc1e',
    messagingSenderId: '462143934523',
    projectId: 'fir-a2f69',
    storageBucket: 'fir-a2f69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa9bgYzAY46H03jSKCpjFNWf1zryTV3Vc',
    appId: '1:462143934523:ios:e4d7639071d636ee27cc1e',
    messagingSenderId: '462143934523',
    projectId: 'fir-a2f69',
    storageBucket: 'fir-a2f69.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa9bgYzAY46H03jSKCpjFNWf1zryTV3Vc',
    appId: '1:462143934523:ios:74321681b40ac42327cc1e',
    messagingSenderId: '462143934523',
    projectId: 'fir-a2f69',
    storageBucket: 'fir-a2f69.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
